### ISSUE TITLE
others support

### ISSUE THREAD

**Issue by jcmartins** [fln/nf9packet#2]
Hi,
do you have plans to implement juniper flow, sflow, mikrotik, huawei?

tks

**Comment by fln** [comment]
In short - no. Addrwatch is designed monitor addresses by passively inspecting activity in the network (without any support from the network equipment). Collecting data via netflow or sflow would require a different application architecture.

**Comment by fln** [comment]
No, this package is just for netflow v9 only.

It provides a low level protocol bindings, it would be best for different protocols to be implemented in different packages.
